config/routes.rb
Rails.application.routes.draw do
  resources :songs
  resources :artists
  resources :genres
  devise_for :users
  
  root to: "pages#index"
  
  post "/songs/:id/:type/buy", to: "songs#buy", as: "buy"
  get "/songs/:id/:type/success", to: "songs#success", as: "success"
  get "/songs/:id/cancel", to: "songs#cancel", as: "cancel"
  
  get "/genre_songs/:genre", to: "genres#genre_songs", as: "genre_songs"
  
  get "/admin", to: "pages#admin", as: "admin"
  get "/account", to: "pages#account", as: "account"
  get "/purchases", to: "pages#purchases", as: "purchases"
  get "/user/:id/:role", to: "pages#change_role", as: "change_role"
  get "/search", to: "pages#search", as: "search"
  post "/search_results/:type", to: "pages#search_results", as: "search_results"
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :songs, dependent: :destroy
  
  validates :image, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5.megabytes }
  validates :name, presence: true, uniqueness: true, length: { maximum: 50, too_long: "must be a maximum of %{count} characters" }
  validates :email, presence: true, length: { maximum: 100, too_long: "must be a maximum of %{count} characters" }
  validates :description, presence: true, length: { maximum: 250, too_long: "must be a maximum of %{count} characters" }
  validates :website, length: { maximum: 100, too_long: "must be a maximum of %{count} characters" }
  
  scope :with_attached_image, -> { includes(image_attachment: :blob) }
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_role, only: [:edit]
  before_action :check_block
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    # select all artists with attached images & their associated songs, ordering results by artist name
    @artists = Artist.paginate(page: params[:page], per_page: 9).includes(:songs).with_attached_image.order(:name)
  end

  def show
    # select all artist songs with their genres
    @songs = @artist.songs.paginate(page: params[:page], per_page: 9).includes(:genres)
  end

  def new
    @artist = Artist.new
  end

  def create
    artist = Artist.create(artist_params)

    if artist.id.nil?
      flash[:alert] = artist.errors.full_messages.join(" | ").upcase
      redirect_to new_artist_path
    else
      if !artist.image.attached?
        artist.image.attach(
          io: File.open("app/assets/images/artist.png"),
          filename: "artist.png",
          content_type: "image/png",
          identify: false
        )
      end
      current_user.add_role(:artist)
      redirect_to artist_path(artist)
    end
  end

  def edit
  end

  def update
    @artist.update(artist_params)
    redirect_to artist_path(@artist)
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private

  def set_artist
    # selects artist including artist image by id
    @artist = Artist.includes(image_attachment: :blob).find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name, :email, :description, :website, :image, :user_id)
  end

  def check_role
    if user_signed_in? && !(@rolls.include?("admin") || @usr.artists.ids.include?(params[:id].to_i))
      flash[:alert] = "Only the artist can edit their profile"
      redirect_to artists_path
    end
  end

  def check_block
    if user_signed_in? && @rolls.include?("blocked")
      flash[:alert] = "Your account has been blocked. Please contact an administrator"
      redirect_to root_path
    end
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_artistdetails.html.erb
<%= form_with model: @artist, local: true do |f| %>
    <div>
        <%= f.label :name, class: "label" %>
        <%= f.text_field :name, class: "input" %>
    </div>
    <div>
        <%= f.label :email, class: "label" %>
        <%= f.email_field :email, class: "input" %>
    </div>
    <div>
        <%= f.label :description, class: "label" %>
        <%= f.text_area :description, class: "textarea", rows: 3 %>
    </div>
    <div>
        <%= f.label :website, class: "label" %>
        <%= f.url_field :website, class: "input" %>
    </div>
    <div>
        <%= f.label :image, class: "label" %>
        <%= f.file_field :image, accept: "image/png, image/jpg, image/jpeg", class: "button is-ghost" %>
        <p class="help is-black">
            png/jpg/jpeg files only
        </p>
    </div><br />
    <%= f.hidden_field :user_id, value: current_user.id %>
    <div>
        <%= f.submit "Create Artist", class: "button is-link" %>
    </div>
<% end %>

app/views/artists/create.html.erb
<h1>Artists#create</h1>
<p>Find me in app/views/artists/create.html.erb</p>

app/views/artists/destroy.html.erb
<h1>Artists#destroy</h1>
<p>Find me in app/views/artists/destroy.html.erb</p>

app/views/artists/edit.html.erb
<section class="hero is-small is-dark">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                EDIT ARTIST DETAILS
            </h1>
            <h2 class="subtitle is-6">
            
            </h2>
        </div>
    </div>
</section>

<section class="section is-centered">
    <%= render "artistdetails" %>
</section>

app/views/artists/index.html.erb
<section class="hero is-small is-dark">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                ARTISTS
            </h1>
        </div>
    </div>
</section>

<section class="section is-centered">
    <div class="container">
        <% if user_signed_in? %>
        <%= link_to "CREATE ARTIST PROFILE", new_artist_path, class: "button is-medium is-link" %>
            <hr>
        <% end %>
        <%= render partial: "shared/artists" %>
    </div>
</section>

<section class="section is-centered">
    <div class="container">
        <%= will_paginate @artists %>
    </div>
</section>

app/views/artists/new.html.erb
<section class="hero is-small is-dark">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                CREATE ARTIST PROFILE
            </h1>
            <h2 class="subtitle is-6">
                create an artist profile in order to upload your music
            </h2>
        </div>
    </div>
</section>

<section class="section is-centered">
    <%= render "artistdetails" %>
</section>

app/views/artists/show.html.erb
<section class="hero is-small is-dark">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                <%= @artist.name %>
            </h1>
        </div>
    </div>
</section>

<section class="section is-centered">
    <div class="container">
        <% if @artist.image.attached? %>
            <%= image_tag @artist.image, width: 200 %>
        <% end %>
        <h2 class="subtitle">Artist Bio</h2>
        <p><strong><%= @artist.description %></strong></p>
        <% if @artist.website? %>
            <br><%= link_to "VISIT ARTIST WEBSITE", @artist.website, target: :_blank, class: "button is-link is-outlined" %>
        <% end %>
        <% if user_signed_in? && (@artist.user_id == current_user.id || current_user.has_role?(:admin)) %>
            <br /><br />
            <p><%= link_to "Edit", edit_artist_path(@artist), class: "button is-primary" %> 
            <%= link_to "Delete", artist_path(@artist), method: :delete, data: { confirm: "Are you sure?" }, class: "button is-danger" %></p>
        <% end %>
        <hr>
    </div>

    <div class="container">
        <h2 class="subtitle">Songs by <%= @artist.name %>:</h2>
        <%= render partial: "shared/songs" %>
    </div>
    <section class="section is-centered">
        <div class="container">
            <%= will_paginate @songs %>
        </div>
    </section>
</section>

app/views/artists/update.html.erb
<h1>Artists#update</h1>
<p>Find me in app/views/artists/update.html.erb</p>