config/routes.rb
Rails.application.routes.draw do
  resources :songs
  resources :artists
  resources :genres
  devise_for :users
  
  root to: "pages#index"
  
  post "/songs/:id/:type/buy", to: "songs#buy", as: "buy"
  get "/songs/:id/:type/success", to: "songs#success", as: "success"
  get "/songs/:id/cancel", to: "songs#cancel", as: "cancel"
  
  get "/genre_songs/:genre", to: "genres#genre_songs", as: "genre_songs"
  
  get "/admin", to: "pages#admin", as: "admin"
  get "/account", to: "pages#account", as: "account"
  get "/purchases", to: "pages#purchases", as: "purchases"
  get "/user/:id/:role", to: "pages#change_role", as: "change_role"
  get "/search", to: "pages#search", as: "search"
  post "/search_results/:type", to: "pages#search_results", as: "search_results"
end

app/views/shared/_artists.html.erb
<% @artists.each do |artist| %>
    <article class="media">
        <figure class="media-left">
            <p class="image is-128x128">
                <% if artist.image.attached? %>
                    <%= link_to image_tag(artist.image, class: "is-rounded"), artist_path(artist) %>
                <% end %>
            </p>
        </figure>
        <div class="media-content">
            <div class="content">
                <p>
                    <strong><%= link_to artist.name, artist_path(artist) %></strong><br>
                    <br>
                    <%= artist.description %>
                </p>
            </div>
            <nav class="level is-mobile">
                <div class="level-left">
                    <div class="level-item">
                        <small><%= artist.songs.size %> songs uploaded</small>
                    </div>
                    <div class="level-item">
                        <button class="button is-small"><%= link_to "VIEW ARTIST", artist_path(artist) %></button>
                    </div>
                </div>
            </nav>
        </div>
    </article>
<% end %>

app/views/shared/_genres.html.erb
<% @genres.each do |genre| %>
    <article class="media">
        <div class="media-content">
            <div class="content">
                <p>
                    <strong><%= genre.name %></strong>
                </p>
            </div>
            <nav class="level is-mobile">
                <div class="level-left">
                    <div class="level-item">
                        <small><%= genre.songs.size %> songs available</small>
                    </div>
                    <div class="level-item">
                        <button class="button is-small">
                            <%= link_to "VIEW #{genre.name.upcase} SONGS", genre_songs_path(genre) %>
                        </button>
                    </div>
                </div>
            </nav>
            <% if @roll %>
                <nav class="level is-mobile">
                    <div class="level-left">
                        <div class="level-item">
                            <div class="level-item">
                                <p><%= link_to "Edit", edit_genre_path(genre), class: "button is-small is-primary" %> 
                                <%= link_to "Delete", genre_path(genre), method: :delete, data: { confirm: "Are you sure?" }, class: "button is-small is-danger" %></p>
                            </div>
                        </div>
                    </div>
                </nav>
            <% end %>
        </div>
    </article>
<% end %>

app/views/shared/_nav.html.erb
<div class="container">
  <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to "SOUND // VISION", root_path, class: "navbar-item" %>
        <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
      </div>
      <div class="navbar-menu" id="navMenu">
        <div class="navbar-start">
          <%= link_to "genres", genres_path, class: "navbar-item" %>
          <%= link_to "songs", songs_path, class: "navbar-item" %>
          <%= link_to "artists", artists_path, class: "navbar-item" %>
          <%= link_to "search", search_path, class: "navbar-item" %>
          <% if user_signed_in? %>
            <%= link_to "account", account_path, class: "navbar-item" %>
              <% if @rolls.include?("admin") %>
                  <%= link_to "admin", admin_path, class: "navbar-item" %>
              <% end %>
          <% end %>
        </div>
          <div class="navbar-end">
              <div class="navbar-item">
                  <div class="buttons">
                      <% if user_signed_in? %>
                          <strong><%= link_to "log out", destroy_user_session_path, method: :delete, class: "button is-black is-outlined" %></strong>
                      <% else %>
                        <strong><%= link_to "log in ", new_user_session_path, class: "button is-dark is-outlined" %></strong>
                        <strong><%= link_to "sign up", new_user_registration_path, class: "button is-info is-outlined" %></strong>
                      <% end %>
                  </div>
              </div>
          </div>
      </div>
  </nav>
</div>

<script>
  document.addEventListener('DOMContentLoaded', () => {

    // Get all "navbar-burger" elements
    const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
  
    // Check if there are any navbar burgers
    if ($navbarBurgers.length > 0) {
  
      // Add a click event on each of them
      $navbarBurgers.forEach( el => {
        el.addEventListener('click', () => {
  
          // Get the target from the "data-target" attribute
          const target = el.dataset.target;
          const $target = document.getElementById(target);
  
          // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
          el.classList.toggle('is-active');
          $target.classList.toggle('is-active');
  
        });
      });
    }
  
  });
</script>

app/views/shared/_search.html.erb
<div class="columns is-centered">
    <div class="column has-text-centered">
        <div class="card">
            <div class="card-content">
                <p class="title">
                    <%= form_tag search_results_path(0), method: :post do %>
                        <div class="field has-addons">
                            <div class="control is-expanded">
                                <%= text_field_tag :search, nil, placeholder: "genre", class: "input" %>
                            </div>
                            <div class="control">
                                <%= submit_tag "SEARCH", class: "button is-link" %>
                            </div>
                        </div>
                    <% end %>
                    <strong>search genres</strong>
                </p>
            </div>
        </div>
    </div>
    <div class="column has-text-centered">
        <div class="card">
            <div class="card-content">
                <p class="title">
                    <%= form_tag search_results_path(1), method: :post do %>
                        <div class="field has-addons">
                            <div class="control is-expanded">
                                <%= text_field_tag :search, nil, placeholder: "song", class: "input" %>
                            </div>
                            <div class="control">
                                <%= submit_tag "SEARCH", class: "button is-link" %>
                            </div>
                        </div>
                    <% end %>
                    <strong>search songs</strong>
                </p>
            </div>
        </div>
    </div>
    <div class="column has-text-centered">
        <div class="card">
            <div class="card-content">
                <p class="title">
                    <%= form_tag search_results_path(2), method: :post do %>
                        <div class="field has-addons">
                            <div class="control is-expanded">
                                <%= text_field_tag :search, nil, placeholder: "artist", class: "input" %>
                            </div>
                            <div class="control">
                                <%= submit_tag "SEARCH", class: "button is-link" %>
                            </div>
                        </div>
                    <% end %>
                    <strong>search artists</strong>
                </p>
            </div>
        </div>
    </div>
</div>

app/views/shared/_songs.html.erb
<% @songs.each do |song| %>
    <article class="media">
        <figure class="media-left">
            <p class="image is-64x64">
                <% if song.artist.image.attached? %>
                    <%= link_to image_tag(song.artist.image, class: "is-rounded"), song_path(song) %>
                <% end %>
            </p>
        </figure>
        <div class="media-content">
            <div class="content">
                <p>
                    <span class="icon is-small"><%= image_tag "music.png" %></span>
                    <strong><%= link_to song.name, song_path(song) %></strong><br>
                    by <small><%= link_to song.artist.name, artist_path(song.artist) %></small>
                    <br>
                    <%= song.description %>
                    <br>
                    <span class="tag is-black"><%= song.genres.pluck(:name).join(", ") %></span>
                </p>
            </div>
            <nav class="level is-mobile">
                <div class="level-left">
                    <div class="level-item">
                        <small>$<%= "%.2f" % song.price %> // $<%= "%.2f" % song.exclusive_price %></small>
                    </div>
                    <div class="level-item">
                        <button class="button is-small"><%= link_to "LISTEN // BUY", song_path(song) %></button>
                    </div>
                </div>
            </nav>
        </div>
    </article>
<% end %>