config/routes.rb
Rails.application.routes.draw do
  resources :songs
  resources :artists
  resources :genres
  devise_for :users
  
  root to: "pages#index"
  
  post "/songs/:id/:type/buy", to: "songs#buy", as: "buy"
  get "/songs/:id/:type/success", to: "songs#success", as: "success"
  get "/songs/:id/cancel", to: "songs#cancel", as: "cancel"
  
  get "/genre_songs/:genre", to: "genres#genre_songs", as: "genre_songs"
  
  get "/admin", to: "pages#admin", as: "admin"
  get "/account", to: "pages#account", as: "account"
  get "/purchases", to: "pages#purchases", as: "purchases"
  get "/user/:id/:role", to: "pages#change_role", as: "change_role"
  get "/search", to: "pages#search", as: "search"
  post "/search_results/:type", to: "pages#search_results", as: "search_results"
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  has_one_attached :song_file
  
  has_many :songs_genre, dependent: :destroy
  has_many :genres, through: :songs_genre

  has_many :user_song, dependent: :destroy
  has_many :users, through: :user_song

  attribute :purchases, default: 0
  attribute :available, default: true

  validates :song_file, presence: true, blob: { content_type: ['audio/mpeg', 'audio/wav'], size_range: 0..100.megabytes }
  validates :name, presence: true, length: { maximum: 50, too_long: "must be a maximum of %{count} characters" }
  validates :description, length: { maximum: 250, too_long: "must be a maximum of %{count} characters" }
  validates :price, numericality: { greater_than_or_equal_to: 0.8, message: "Minimum price is $0.80" }
  validates :exclusive_price, numericality: { greater_than_or_equal_to: 1, message: "Minimum price is $1.00" }
  validates :artist, presence: true
  validates :genres, presence: true

  def self.search(search)
    where("lower(artists.name) LIKE :search OR lower(songs.name) LIKE :search", search: "%#{search.downcase}%")
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:buy]
  before_action :authenticate_user!, except: [:buy, :index]
  before_action :check_role, only: [:new]
  before_action :check_artist, only: [:edit]
  before_action :check_block
  before_action :set_song, except: [:index, :new, :create]
  before_action :set_user_artists, only: [:new, :edit]
  before_action :set_genres, only: [:show, :edit, :update, :new]

  def index
    # select all songs & their related genres and artist's image, order results by song name
    @songs = Song.paginate(page: params[:page], per_page: 9).includes(:genres, artist: :image_blob).order(:name)
  end

  def show
    @purchased = true if @song.purchases >= 1
    @user_owned = true if current_user.songs.include?(@song)
    @sole_owner = true if @song.users.size == 1 && @song.user_ids.include?(current_user.id)
    @song_genres = @song.genres.pluck(:name).join(", ")
  end

  def new
    @song = Song.new
  end

  def create
    song = Song.create(song_params)
    if song.id.nil?
      flash[:alert] = song.errors.full_messages.join(" | ").upcase
      redirect_to new_song_path(song)
    else
      redirect_to song_path(song)
    end
  end

  def edit
  end

  def update
    @song.update(song_params)
    redirect_to song_path(@song)
  end

  def destroy
    @song.destroy
    redirect_to songs_path
  end

  def buy
    price = nil

    case params[:type].to_i
    when 1
      price = @song.price
    when 2
      price = @song.exclusive_price
    end
    
    Stripe.api_key = ENV['STRIPE_API_KEY']

    session = Stripe::Checkout::Session.create({
        payment_method_types: ['card'],
        mode: 'payment',
        customer_email: current_user.email,
        success_url: success_url(params[:id], params[:type]),
        cancel_url: cancel_url(params[:id]),
        line_items: [
          {
            price_data: {
              currency: 'aud',
              product_data: {
                name: "#{@song.name} - song by #{@song.artist.name}",
                description: @song.description,
                images: [url_for(@song.artist.image)]
              },
              unit_amount: (price.to_f * 100).to_i
            },
            quantity: 1
          }
        ]
    })

    render json: session
  end

  def success
    if params[:type] == "2" && @song.available
      @song.update_attribute(:available, false)
    end
    
    if !current_user.songs.ids.include?(@song.id)
      @song.increment!(:purchases)
      UserSong.create(user_id: current_user.id, song_id: @song.id)
      UserMailer.purchase_email(current_user, @song, params[:type]).deliver
      UserMailer.artist_purchase_notification(@song, params[:type]).deliver
    end
  end

  def cancel
  end

  private

  def set_song
    # selects song by id & includes related genres and artist image
    @song = Song.includes(:genres, artist: :image_blob).find(params[:id])
  end

  def set_user_artists
    # select artist with a user_id matching current user id
    @artists = Artist.where(user_id: current_user.id)
  end

  def set_genres
    # selects all genres
    @genres = Genre.all
  end

  def song_params
    params.require(:song).permit(:song_file, :name, :description, :price, :exclusive_price, :artist_id, genre_ids: [])
  end

  def check_role
    if user_signed_in? && !@rolls.include?("artist")
      flash[:alert] = "You need to have an artist profile in order to do that"
      redirect_to songs_path
    end
  end

  def check_artist
    if user_signed_in? && !(@usr.id == Song.find(params[:id].to_i).artist.user_id)
      flash[:alert] = "Only the artist can edit their own song"
      redirect_to songs_path
    end
  end

  def check_block
    if user_signed_in? && @rolls.include?("blocked")
      flash[:alert] = "Your account has been blocked. Please contact an administrator"
      redirect_to root_path
    end
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_songdetails.html.erb
<%= form_with model: @song, local: true do |f| %>
    <div>
        <%= f.label :song_file, class: "label" %>
        <%= f.file_field :song_file, accept: "audio/mpeg, audio/wav", class: "button is-ghost" %>
        <p class="help is-black">
            mp3/wav files only
        </p><br />
    </div>
    <div>
        <%= f.label :name, class: "label" %>
        <%= f.text_field :name, class: "input" %>
    </div>
    <div>
        <%= f.label :description, class: "label" %>
        <%= f.text_area :description, class: "textarea", rows: 3 %>
    </div>
    <div>
        <%= f.label :price, class: "label" %>
        <%= f.number_field :price, step: 0.1, class: "input" %>
        <p class="help is-danger">
            Minimum price is $0.80
       </p><br />
    </div>
    <div>
        <%= f.label :exclusive_price, class: "label" %>
        <%= f.number_field :exclusive_price, step: 0.1, class: "input" %>
        <p class="help is-danger">
             Exclusive purchases are a one-time purchase - the song can't be purchased again - so the exclusive price is usually set higher (minimum is $1.00)
        </p><br />
    </div>
    <%= f.label :artist_id, class: "label" %>
    <div class="select">
        <%= f.select(:artist_id, @artists.map { |a| [a.name, a.id] }) %>
    </div>
    <%= f.label :genres, class: "label" %>
    <div class="checkbox">
        <p><%= f.collection_check_boxes :genre_ids, @genres, :id, :name %></p>
    </div><br /><br />
    <div>
        <%= f.submit "Create Song", class: "button is-link" %>
    </div>
<% end %>

app/views/songs/cancel.html.erb
<section class="hero is-small is-danger">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                TRANSACTION CANCELLED
            </h1>
        </div>
    </div>
</section>

<section class="section is-centered">
    <div class="container">
        <h3><%= link_to "Return to Song Page", song_path(), class: "button is-black" %></h3>
    </div>
</section>

app/views/songs/create.html.erb
<h1>Songs#create</h1>
<p>Find me in app/views/songs/create.html.erb</p>

app/views/songs/destroy.html.erb
<h1>Songs#destroy</h1>
<p>Find me in app/views/songs/destroy.html.erb</p>

app/views/songs/edit.html.erb
<section class="hero is-small is-dark">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                EDIT <%= @song.name %>
            </h1>
            <h2 class="subtitle is-6">
            
            </h2>
        </div>
    </div>
</section>

<section class="section is-centered">
    <%= render "songdetails" %>
</section>

app/views/songs/index.html.erb
<section class="hero is-small is-dark">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                SONGS
            </h1>
        </div>
    </div>
</section>

<section class="section is-centered">
    <div class="container">
        <% if user_signed_in? && current_user.has_role?(:artist) %>
            <%= link_to "UPLOAD SONG", new_song_path, class: "button is-medium is-link" %>
            <hr>
        <% end %>
        <%= render partial: "shared/songs" %>
    </div>
</section>

<section class="section is-centered">
    <div class="container">
        <%= will_paginate @songs %>
    </div>
</section>

app/views/songs/new.html.erb
<section class="hero is-small is-dark">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                UPLOAD SONG
            </h1>
            <h2 class="subtitle is-6">
            
            </h2>
        </div>
    </div>
</section>

<section class="section is-centered">
    <%= render "songdetails" %>
</section>

app/views/songs/show.html.erb
<section class="hero is-small is-dark">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                <%= @song.name %>
            </h1>
        </div>
    </div>
</section>

<section class="section is-centered">
    <div class="container">
        <p class="image is-128x128">
            <% if @song.artist.image.attached? %>
                <%= link_to image_tag(@song.artist.image, class: "is-rounded"), artist_path(@song.artist) %>
            <% end %>
        </p>

        <h4 class="subtitle is-4">by <%= link_to @song.artist.name, artist_path(@song.artist) %></h4>

        <% if @song.song_file.attached? && @song.available %>
            <div class="level">
                <audio controls>
                    <source src=<%= url_for(@song.song_file) %> type="audio/mpeg">
                    <source src=<%= url_for(@song.song_file) %> type="audio/ogg">
                    <source src=<%= url_for(@song.song_file) %> type="audio/mpeg">
                </audio>
            </div>
        <% end %>

        <div class="media-content">
            <div class="content">
                <p>
                    <span class="tag is-black"><%= @song_genres %></span>
                </p>
            </div>
        </div>
    </div>

    <hr>

    <div class="container">
        <%= @song.description %>
    </div>

    <script src="https://js.stripe.com/v3/"></script>

    <% if @song.available %>
        <div class="container">
            <br />
            <% if @user_owned %>
                <h4><%= link_to "Purchased on #{current_user.user_song.first.created_at}", purchases_path, class: "button is-black is-outlined" %></h4>
            <% else %>
                <button id="buynow" class="button is-link is-outlined"><%= "BUY FOR $%.2f" % @song.price %></button>
                
                <script>
                    const stripe = Stripe("<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>")
                    const buyButton = document.getElementById('buynow')

                    buyButton.addEventListener('click', function() {
                        fetch('<%= buy_path(@song.id, 1) %>', {
                            method: 'POST'
                        })
                        .then(function(response) {
                            return response.json()
                        })
                        .then(function(session) {
                            return stripe.redirectToCheckout({ sessionId: session.id })
                        })
                    })
                </script>
            <% end %>
        </div>
        <div class="container">
            <br />
            <% if @purchased && @sole_owner || !@purchased %>
                <button id="excl" class="button is-link"><%= "EXCLUSIVE PRICE $%.2f" % @song.exclusive_price %></button>
                <br /><br />
                <p>
                    <i>Exclusive purchase prices are usually higher because once you purchase this song, it is no longer available for other users to buy - it is uniquely yours!
                    <br>
                    The artist grants you full use of this song provided you credit them as the composer.</i>
                </p>

                <script>
                    const buyButton2 = document.getElementById('excl')

                    buyButton2.addEventListener('click', function() {
                        fetch('<%= buy_path(@song.id, 2) %>', {
                            method: 'POST'
                        })
                        .then(function(response) {
                            return response.json()
                        })
                        .then(function(session) {
                            return stripe.redirectToCheckout({ sessionId: session.id })
                        })
                    })
                </script>
            <% elsif @purchased && !@sole_owner %>
                <p>Exclusive purchase unavailable</p>
            <% end %>
        </div>
    
    <% elsif !@song.available && !@user_owned %>
        <div class="container">
            <h4>Song no longer available - already purchased exclusively</h4>
        </div>
    <% elsif !@song.available && @user_owned %>
        <div class="container">
            <h4>Congratulations - you own this song exclusively!</h4>
        </div>
    <% end %>

    <div class="container">
        <% if @song.artist.user_id == current_user.id %>
            <br /><br />
            <p><%= link_to "Edit", edit_song_path(@song), class: "button is-primary" %> 
                <%= link_to "Delete", song_path(@song), method: :delete, data: { confirm: "Are you sure?" }, class: "button is-danger" %></p>
        <% end %>
    </div>
</section>

app/views/songs/success.html.erb
<section class="hero is-small is-success">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                PAYMENT SUCCESSFUL
            </h1>
        </div>
    </div>
</section>

<section class="section is-centered">
    <div class="container">
        <h3 class="subtitle is-5">Thank you for buying <strong><%= @song.name %></strong> by <strong><%= @song.artist.name %></strong></h3>
        <%= link_to "DOWNLOAD", rails_blob_path(@song.song_file, disposition: 'attachment'), class: "button is-link" %>
        <hr>
        <p>
            You can access your purchased song at any time in <%= link_to "Account > View Purchased Songs", purchases_path, class: "button is-link is-outlined is-small" %>
        </p>
        <hr>
        <h3><%= link_to "Return to Song List", songs_path, class: "button is-success" %></h3>
    </div>
</section>

app/views/songs/update.html.erb
<h1>Songs#update</h1>
<p>Find me in app/views/songs/update.html.erb</p>