config/routes.rb
Rails.application.routes.draw do
  resources :songs
  resources :artists
  resources :genres
  devise_for :users
  
  root to: "pages#index"
  
  post "/songs/:id/:type/buy", to: "songs#buy", as: "buy"
  get "/songs/:id/:type/success", to: "songs#success", as: "success"
  get "/songs/:id/cancel", to: "songs#cancel", as: "cancel"
  
  get "/genre_songs/:genre", to: "genres#genre_songs", as: "genre_songs"
  
  get "/admin", to: "pages#admin", as: "admin"
  get "/account", to: "pages#account", as: "account"
  get "/purchases", to: "pages#purchases", as: "purchases"
  get "/user/:id/:role", to: "pages#change_role", as: "change_role"
  get "/search", to: "pages#search", as: "search"
  post "/search_results/:type", to: "pages#search_results", as: "search_results"
end

app/views/pages/account.html.erb
<section class="hero is-small is-dark">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                MY ACCOUNT
            </h1>
            <h2 class="subtitle is-6">
                edit your details, find your purchases, view your artist profiles
            </h2>
        </div>
    </div>
</section>

<section class="section is-centered">
    <div class="container">
        <article class="media">
            <div class="media-content">
                <div class="content">
                    <p>
                        <h2 class="subtitle is-5"><strong><%= "#{@user.first_name} #{@user.last_name}" %></strong></h2>
                        <%= @user.email %>
                        <%= link_to "Edit", edit_user_registration_path, class: "button is-link is-outlined is-small" %>
                    </p>
                </div>
            </div>
        </article>

        <hr>
        
        <% if @user.songs.size > 0 %>
            <p><%= link_to "VIEW PURCHASED SONGS", purchases_path, class: "button is-link is-outlined" %></p>
        <% else %>
            <p>You have not purchased any songs yet</p>
        <% end %>
        
        <hr>

        <h3 class="subtitle is-4">MY ARTIST PROFILES</h3>
        <% if @rolls.include?("artist") %>
            <%= render partial: "shared/artists" %>
        <% else %>
            <p>You do not have an artist account. Create one <%= link_to "here", new_artist_path %> in order to upload your music.</p>
        <% end %>
    </div>
</section>

<% if @rolls.include?("artist") %>
    <section class="section is-centered">
        <div class="container">
            <%= will_paginate @artists %>
        </div>
    </section>
<% end %>

app/views/pages/admin.html.erb
<section class="hero is-small is-dark">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                SITE ADMINISTRATION
            </h1>
            <h2 class="subtitle is-6">
                manage user roles
            </h2>
        </div>
    </div>
</section>

<section class="section is-centered">
    <div class="container">
        <h3 class="subtitle">USERS</h3>

        <% @users.each do |user| %>
            <article class="media">
                <div class="media-content">
                    <div class="content">
                        <p>
                            <h2 class="subtitle is-5"><strong><%= user.first_name %> <%= user.last_name %></strong></h2>
                            <%= user.email %>
                            <span class="tag is-primary"><%= user.roles.pluck(:name).join(", ") %></span>
                        </p>
                    </div>
                    <nav class="level is-mobile">
                        <div class="level-left">
                            <div class="level-item">
                                <p><%= link_to "Admin", change_role_path(user, 0), class: "button is-link is-small is-outlined" %> 
                                <%= link_to "Artist", change_role_path(user, 1), class: "button is-primary is-small is-outlined" %> 
                                <%= link_to "Block", change_role_path(user, 2), class: "button is-danger is-small is-outlined" %></p>
                            </div>
                        </div>
                    </nav>
                </div>
            </article>
        <% end %>
    </div>
</section>

<section class="section is-centered">
    <div class="container">
        <%= will_paginate @users %>
    </div>
</section>

app/views/pages/genre_songs.html.erb
<section class="hero is-small is-dark">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                <%= @genre.upcase %> SONGS
            </h1>
            <h2 class="subtitle is-6">
            
            </h2>
        </div>
    </div>
</section>

<section class="section is-centered">
    <%= render partial: "shared/songs" %>
</section>

app/views/pages/home.html.erb
<h1>SOUND & VISION</h1>
<p>Music market for media content creators</p>

app/views/pages/index.html.erb
<section class="hero is-small is-dark">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title is-1">
        SOUND // VISION
      </h1>
      <h2 class="subtitle is-6">
        music market for media content creators
      </h2>
    </div>
  </div>
</section>

<%= image_tag "soundvision.png", class: "image", style: "width: 100%; height: 300px; object-fit: cover;" %>

<section class="section is-centered">
  <div class="columns is-centered">
    <div class="column has-text-centered">
      <div class="card">
        <div class="card-content">
          <p class="title">
            <%= link_to "GENRES", genres_path %>
          </p>
          <p class="subtitle is-6">
            find music by genre/style
          </p>
          </div>
        </div>
      </div>
    <div class="column has-text-centered">
      <div class="card">
        <div class="card-content">
          <p class="title">
            <%= link_to "SONGS", songs_path %>
          </p>
          <p class="subtitle is-6">
            music uploaded by SOUND // VISION artists
          </p>
        </div>
      </div>
    </div>
    <div class="column has-text-centered">
      <div class="card">
        <div class="card-content">
          <p class="title">
            <%= link_to "ARTISTS", artists_path %>
          </p>
          <p class="subtitle is-6">
            browse SOUND // VISION artists
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="columns is-centered">
    <div class="column has-text-centered">
      <div class="card">
        <div class="card-content">
          <p class="title">
            <%= link_to "SEARCH", search_path %>
          </p>
          <p class="subtitle is-6">
            search genres // songs // artists
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/purchases.html.erb
<section class="hero is-small is-dark">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                YOUR PURCHASED SONGS
            </h1>
            <h2 class="subtitle is-6">
                a list of all the songs you have purchased with download links
            </h2>
        </div>
    </div>
</section>

<section class="section is-centered">
    <div class="container">
        <% @user_songs.each do |song| %>
            <article class="media">
                <figure class="media-left">
                    <p class="image is-128x128">
                        <% if song.artist.image.attached? %>
                            <%= link_to image_tag(song.artist.image, class: "is-rounded"), song_path(song) %>
                        <% end %>
                    </p>
                </figure>
                <div class="media-content">
                    <div class="content">
                        <p>
                            <span class="icon is-small"><%= image_tag "music.png" %></span>
                            <strong><%= link_to song.name, song_path(song) %></strong><br>
                            by <small><%= link_to song.artist.name, artist_path(song.artist) %></small>
                            <br>
                            <%= song.description %>
                            <br>
                            <span class="tag is-black"><%= song.genres.pluck(:name).join(", ") %></span>
                        </p>
                    </div>
                    <nav class="level is-mobile">
                        <div class="level-left">
                            <div class="level-item">
                                <button class="button is-small"><%= link_to "Download", rails_blob_path(song.song_file, disposition: 'attachment') %></button>
                            </div>
                        </div>
                    </nav>
                </div>
            </article>
        <% end %>
    </div>
</section>

<section class="section is-centered">
    <div class="container">
        <%= will_paginate @user_songs %>
    </div>
</section>

app/views/pages/search.html.erb
<section class="hero is-small is-dark">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                SEARCH
            </h1>
            <h2 class="subtitle is-6">
                genres // songs // artists
            </h2>
        </div>
    </div>
</section>

<section class="section is-centered">
    <%= render partial: "shared/search" %>
</section>

app/views/pages/search_results.html.erb
<section class="hero is-small is-dark">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                SEARCH
            </h1>
            <h2 class="subtitle is-4">
                <%= @search_type %> search results for "<%= @parameter %>"
            </h2>
        </div>
    </div>
</section>

<section class="section is-centered">
    <div class="container">
        <p class="subtitle"><%= @result_count %> results found:</p>
        <% if @type == 0 %>
            <%= render partial: "shared/genres" %>
        <% elsif @type == 1 %>
            <%= render partial: "shared/songs" %>
        <% elsif @type == 2 %>
            <%= render partial: "shared/artists" %>
        <% end %>
    </div>

    <br />
    <%= render partial: "shared/search" %>
</section>